### ISSUE TITLE
error in console output!!!

### ISSUE THREAD

**Issue by shadow-absorber** [catppuccin/sioyek#4]
```
Error: required 3 values for color, but got 1
Error in config file /home/USER/.config/sioyek/prefs_user.config at line 5 : visual_mark_color          #7f849c
```

**Comment by 21st-centuryman** [comment]
That's odd I haven't seen anything like it on my end. Can you send me your configuration file?

**Comment by shadow-absorber** [comment]
> That's odd I haven't seen anything like it on my end. Can you send me your configuration file?

```
# === CATPPUCCIN MOCHA === #
background_color           #1e1e2e

text_highlight_color       #f9e2af
visual_mark_color          #7f849c

search_highlight_color     #f9e2af
link_highlight_color       #89b4fa
synctex_highlight_color    #a6e3a1

highlight_color_a          #f9e2af
highlight_color_b          #a6e3a1
highlight_color_c          #89dceb
highlight_color_d          #eba0ac
highlight_color_e          #cba6f7
highlight_color_f          #f38ba8
highlight_color_g          #f9e2af


custom_background_color    #1e1e2e
custom_text_color          #cdd6f4

ui_text_color              #cdd6f4
ui_background_color        #313244
ui_selected_text_color     #cdd6f4
ui_selected_background_color #585b70
```
prefs_user.config

**Comment by 21st-centuryman** [comment]
Your configuration worked on my end using sioyek 2.0
```
$ sioyek --version
sioyek 2.0.0
```
are you using a different version?

**Comment by shadow-absorber** [comment]
> Your configuration worked on my end using sioyek 2.0
> 
> ```
> $ sioyek --version
> sioyek 2.0.0
> ```
> 
> are you using a different version?

```
❯ paru -Qs sioyek
local/sioyek 2.0.0-7
    PDF viewer for research papers and technical books.
```
from arch linux

**Comment by JustAnAverageGuy** [comment]
Can confirm 

```
Error: required 3 values for color, but got 1
Error in config file /home/USER/.config/sioyek/themes/catppuccin-mocha.config at line 5 : visual_mark_color          #7f849c
```

```
$ sioyek --version
sioyek 2.0.0
```

On ubuntu 24.04

---

After some digging, the error stems from the fact that the sioyek documentation defines colors as 
`r g b a` where each component is a value between 0 and 1, for some reason it seems to work with hex colors by default as well but it seems unintended.

**Comment by 21st-centuryman** [comment]
Hmm ok understood. I was not able to replicate it I will look into this further within the coming days

**Comment by JustAnAverageGuy** [comment]
For the record, sioyek loads up fine and other colors from the colorscheme also get applied despite the log showing an error.

**Comment by 21st-centuryman** [comment]
I looked into this.
Since the rga values are between 1 and 0 I do not feel comfortable adding these values as catppuccin do not have any offical resources on this, its etiher, hex, rgb wiht 255 or hsl.  

hex color support is officially supported so this error is most likely just a bug in sioyek's terminal. 
https://github.com/ahrm/sioyek/commit/ea4b1dcc3f16079cec04f6cd565aec54da855adc
https://github.com/ahrm/sioyek/issues/373

I will therefore close this issue. If you want to continue this I would recommend adding an issue to [sioyek](https://github.com/ahrm/sioyek) directly
